# Generated by Django 4.0.3 on 2022-05-11 00:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_serviceappointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='vin',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='automobile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service_rest.automobilevo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
