# Generated by Django 4.0.3 on 2022-05-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_technician_employee_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='status',
            field=models.CharField(default='IN_PROGRESS', max_length=100),
        ),
    ]
